repository_type: pipeline

nf_core_version: 3.2.0

lint: {}

template:
  org: nf-core
  name: multilocus
  description: Generate multilocus sequence data from short reads
  author: Yuttapong Thawornwattana
  version: 1.0.0dev
  force: true
  outdir: .
  is_nfcore: true
